name: 'Close stale issues and PRs'

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '30 11 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 30
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 30 days if no further activity occurs.
            If this is still relevant, please add a comment or apply an exempt label.
          close-issue-message: >
            Closing this issue due to prolonged inactivity. Feel free to reopen
            or open a new issue if the problem persists.
          stale-pr-message: >
            This pull request has been marked as stale due to inactivity.
            It will be closed in 30 days if no further updates are made.
          close-pr-message: >
            Closing this pull request due to prolonged inactivity.
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,blocked,good first issue,help wanted,do-not-close,wip'
          exempt-pr-labels: 'blocked,wip,do-not-close'
          exempt-draft-prs: true
          remove-stale-when-updated: true
          operations-per-run: 200
          enable-statistics: true
